### PR TITLE
Update to Jekyll v4

### PR DESCRIPTION
**Pull request by furilo**

### CODE REVIEW

**Comment by furilo** [comment]
@ferblape deploy is working to Cloudflare pages. Review site: https://7699b85d.populate-tools.pages.dev/

And maybe we can get rid of Netlify for pro - If I'm not wrong we'd just have to merge to pro and change the DNS.

**Comment by furilo** [comment]
Mmm, I'm seeing some problems in paths on here https://7699b85d.populate-tools.pages.dev/es/blog/exploracion-poblacion

**Comment by furilo** [comment]
On it

**Comment by furilo** [comment]
@ferblape please review https://update-jekyllv4.populate-tools.pages.dev/ 

I think we can merge + change the DNS

**Review by ferblape — APPROVED** [review]
Let's go! Should I change the DNS?

**Comment by ferblape** [comment]
Done

Screenshot 2024-11-27 at 16 47 51

**Comment by furilo** [comment]
Great, I think we can delete the Netlify project

**Pull request merged**
